import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { motion } from "framer-motion"
import { useEffect, useState } from 'react'
import ScrollTrigger from "gsap/dist/ScrollTrigger";

import { gsap } from "gsap";
gsap.registerPlugin(ScrollTrigger);


const Hover = {
  image: {
    skewY: 1,
    scale: 1.1,
    overFlow: "hidden",
    filter: `drop-shadow(0px 354px 142px rgba(32, 37, 42, 0.02)) drop-shadow(0px 199px 119px rgba(32, 37, 42, 0.05)) 
    `



  },
  transition: {
    type: 'spring',

    when: 'beforeChildren'
  }
}
const popImage = {
  image: {
    opacity: 1,
    scale: 1,
    zIndex: 9999,
    x: 50,
    y: -50,


    transition: {
      type: 'spring',



    }



  },
  init: {
    width: '0rem',
    opacity: 0,
    height: '1rem',
    color: "red",


  },
}
/*  filter: `drop-shadow(0px 354px 142px rgba(32, 37, 42, 0.01)) drop-shadow(0px 199px 119px rgba(32, 37, 42, 0.05)) 
    drop-shadow(0px 88px 88px rgba(32, 37, 42, 0.09))
     drop-shadow(0px 22px 49px rgba(32, 37, 42, 0.1)) 
    drop-shadow(0px 0px 0px rgba(32, 37, 42, 0.1))`*/
export default function Home() {

  useEffect(() => {
    console.log("useffetc called agai")
    const cursor = (event: any) => {
      if (mouseCurouser) {
        mouseCurouser.style.left = event.clientX + "px"
        mouseCurouser.style.top = event.clientY + "px";


      }
      if (ProjectImage) {

        ProjectImage.forEach(image => {
          image.addEventListener('mouseover', () => {
            outter?.classList.add("scale-[4]", "opacity-1", "bg-[#F26527]");

            outterText?.classList.add('text-opacity');
          })

        })

        ProjectImage.forEach(image => {
          image.addEventListener('mouseleave', () => {
            outter?.classList.remove("scale-[4]");
            outterText?.classList.remove('text-opacity');
          })

        })
      }

    }
    const mouseCurouser = document.querySelector('.cursor');
    //project-image
    const ProjectImage = document.querySelectorAll('.project-image');
    const outter = document.querySelector('.outter')
    const outterText = document.querySelector('.outterText')
    window.addEventListener("mousemove", cursor)





  })



  return (
    <>

      <div className={styles.container}>

        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>

          <div className='flex flex-col w-80 sm:w-96 md:w-10/12 md:items-center relative'>
            <div>
              <div className="relative">
                <motion.div
                  initial={{
                    y: 5,

                  }}
                  animate={{
                    y: 0,


                  }}
                  transition={{
                    yoyo: Infinity,



                  }}
                  style={{}} className='w-24  h-1 bg-[#F5803E] absolute -top-2'></motion.div>

                <h3 className="font-Poppins leading-8	 text-[#0B1727] font-bold text-2xl">A DEVELOPER WITH AN EYE FOR PRODUCT AND USER EXPERIENCE</h3>
              </div>
              <div className="w-80 mt-4 md:w-10/12 sm:w-96">
                <p className="font-Poppins leading-5 text-[#2E435F] text-sm">I will help you design a Minimalistic, and intuitive user interface that will enthrall and engage your users. </p>
              </div>
            </div>
            <div className="flex flex-col items-center md:flex-row md:mt-32">
              <button style={{
                boxShadow: "0px 58px 23px rgba(121, 113, 234, 0.01), 0px 32px 19px rgba(121, 113, 234, 0.05), 0px 14px 14px rgba(121, 113, 234, 0.09), 0px 4px 8px rgba(121, 113, 234, 0.1), 0px 0px 0px rgba(121, 113, 234, 0.1)"
              }} className="  bg-[#576E92] h-14 w-52 mb-24 mt-20 md:mt-0 md:mb-0 md:mr-32"><span className="font-Poppins text-white">View My Work</span></button>

              <button className="  bg-[#DCE0E6] h-14 w-52" style={{ boxShadow: '0px 87px 35px rgba(11, 23, 39, 0.01), 0px 49px 29px rgba(11, 23, 39, 0.05), 0px 22px 22px rgba(11, 23, 39, 0.09), 0px 5px 12px rgba(11, 23, 39, 0.1), 0px 0px 0px rgba(11, 23, 39, 0.1)' }}>
                <span className='text-[#0B1727] font-Poppins'>Contact Me</span></button>
            </div>
          </div>
          <div className="w-80 md:w-10/12 lg:w-10/12 xl:w-5/12 sm:w-96 mt-48">
            <p className="font-Poppins text-2xl max-[500px]:text-xl text-[#2E435F] leading-12">Passionate about Technology and obess with learning.
              I love working at the intersection of creativity and User friendly interfaces.</p>
            <motion.button whileHover={{
              scale: 1.1,
              boxShadow: "0px 66px 27px rgba(23, 25, 28, 0.01), 0px 37px 22px rgba(23, 25, 28, 0.05), 0px 17px 17px rgba(23, 25, 28, 0.09), 0px 4px 9px rgba(23, 25, 28, 0.1), 0px 0px 0px rgba(23, 25, 28, 0.1)"
            }} className="  bg-[#324670] h-14 w-52 mt-12 mb-32"><span className="font-Poppins text-white">About me</span></motion.button>
          </div>
          <div className="mt-40 mb-24">
            <h2 className='text-5xl font-bold font-Poppins text-[#0B1727] uppercase'>Latest Project</h2>
          </div>

          <section className="  w-full h-full   justify-center items-center " >

            <div className="  relative ">

              <div className=" flex    w-full justify-center items-center mt-5   lg:flex-row    " id="work-container">


                <div className='  flex max-[1020px]:flex-col    justify-center   items-center mt-10  ' >
                  <motion.div className="relative"
                    variants={Hover} whileHover="image"



                  >

                    <Image src="/companies/Aisle.png" alt="aurora" width={800} height={100} className="project-image object-cover p-2  relative z-88" quality={100} priority />

                    <div className="relative  max-[500px]:hidden  ">
                      <motion.div variants={popImage} initial={{ opacity: 0 }} className="absolute   -z-10 bottom-0  left-[250px]  -top-[300px] w-[200px] h-[200px]">
                        <Image src="/companies/Aisle.png" alt="aurora" width={800} height={100} className="  object-cover p-2  relative z-88" quality={100} priority />

                      </motion.div>
                      <motion.div variants={popImage} initial={{ opacity: 0 }} className="absolute   -z-10 bottom-0  -left-[50px]  -top-[260px] w-[200px] h-[200px]">
                        <Image src="/companies/Aisle.png" alt="aurora" width={800} height={100} className="  object-cover p-2  relative z-88" quality={100} priority />

                      </motion.div>
                      <motion.div

                        variants={popImage} initial={{ opacity: 0 }} className="absolute   -z-10 bottom-0  left-[220px]  top-[5px] w-[200px] h-[200px]">
                        <Image src="/companies/Aisle.png" alt="aurora" width={200} height={200} className="  object-cover p-2  relative z-88" quality={100} priority />

                      </motion.div>



                    </div>

                  </motion.div>
                  <div className='  p-5  max-[900px]:w-[90vw]  lg:w-2/5 xl:w-1/5   left-3  relative  text-[black]'>
                    <h3 className='text-4xl font-bold text-[#63001C]'>Aisle Rocket</h3>
                    <h5 className='text-[#792300]'>front End Developer</h5>
                    <span className="text-[#792300]">2022</span>
                    <p className='lg:w-full md:w-2/3 leading-7 text-[#772406] mt-5'>Aisle Rocket is a digital marketing agency that harnesses the power of data and actionable insights to deliver breakthrough ideas
                      and brand experiences that drive emotional connection and measurable impact.</p> </div>

                </div>







              </div>





            </div>


            <div className="  relative  overflow-hidden">

              <div className=" flex    w-full justify-center items-center mt-5   lg:flex-row    " id="work-container">


                <div className='  flex max-[1020px]:flex-col    justify-center   items-center mt-10  ' >
                  <motion.div className="relative"
                    variants={Hover} whileHover="image"



                  >

                    <Image src="/companies/Aisle.png" alt="aurora" width={800} height={100} className="project-image object-cover p-2  relative z-88" quality={100} priority />

                    <div className="relative  max-[500px]:hidden  ">
                      <motion.div variants={popImage} initial={{ opacity: 0 }} className="absolute   -z-10 bottom-0  left-[250px]  -top-[300px] w-[200px] h-[200px]">
                        <Image src="/companies/Aisle.png" alt="aurora" width={800} height={100} className="  object-cover p-2  relative z-88" quality={100} priority />

                      </motion.div>
                      <motion.div variants={popImage} initial={{ opacity: 0 }} className="absolute   -z-10 bottom-0  -left-[50px]  -top-[260px] w-[200px] h-[200px]">
                        <Image src="/companies/Aisle.png" alt="aurora" width={800} height={100} className="  object-cover p-2  relative z-88" quality={100} priority />

                      </motion.div>
                      <motion.div

                        variants={popImage} initial={{ opacity: 0 }} className="absolute   -z-10 bottom-0  left-[220px]  top-[5px] w-[200px] h-[200px]">
                        <Image src="/companies/Aisle.png" alt="aurora" width={200} height={200} className="  object-cover p-2  relative z-88" quality={100} priority />

                      </motion.div>



                    </div>

                  </motion.div>
                  <div className='  p-5  max-[900px]:w-[90vw]  lg:w-2/5 xl:w-1/5   left-3  relative  text-[black]'>
                    <h3 className='text-4xl font-bold text-[#63001C]'>Aisle Rocket</h3>
                    <h5 className='text-[#792300]'>front End Developer</h5>
                    <span className="text-[#792300]">2022</span>
                    <p className='lg:w-full md:w-2/3 leading-7 text-[#772406] mt-5'>Aisle Rocket is a digital marketing agency that harnesses the power of data and actionable insights to deliver breakthrough ideas
                      and brand experiences that drive emotional connection and measurable impact.</p> </div>

                </div>







              </div>





            </div>
























          </section>

          < div


            className='cursor fixed overflow-hidden border-2  w-14 h-14 rounded-full text-center  '>
            <div className="outter  w-5 h-5 relative  top-4 left-4  rounded-full transition-all duration-500	 ">
            </div>
            <span className=' outterText relative  font-bold text-lg font-Poppins text-hide'>View</span>



          </div>



        </main>


      </div>

    </>
  )
}


/*
      <
      
            <div className="  relative mt-48  mb-14 ">

              <div className=" flex    w-full justify-center items-center mt-5   lg:flex-row    " id="work-container">


                <div className='  flex max-[1020px]:flex-col    flex-row-reverse  justify-center   items-center mt-10  ' >
                  <motion.div className="relative "
                    variants={Hover} whileHover="image"


                  >

                    <Image src="/companies/Aisle.png" alt="aurora" width={800} height={100} className="project-image object-cover p-2  relative z-88" quality={100} priority />

                    <div className="relative   max-[500px]:hidden   ">
                      <motion.div variants={popImage} initial={{ opacity: 0 }} className="absolute   -z-10 bottom-0  left-[250px]  -top-[300px] w-[200px] h-[200px]">
                        <Image src="/companies/Aisle.png" alt="aurora" width={800} height={100} className="  object-cover p-2  relative z-88" quality={100} priority />

                      </motion.div>
                      <motion.div variants={popImage} initial={{ opacity: 0 }} className="absolute   -z-10 bottom-0  -left-[50px]  -top-[260px] w-[200px] h-[200px]">
                        <Image src="/companies/Aisle.png" alt="aurora" width={800} height={100} className="  object-cover p-2  relative z-88" quality={100} priority />

                      </motion.div>
                      <motion.div

                        variants={popImage} initial={{ opacity: 0 }} className="absolute   -z-10 bottom-0  left-[220px]  top-[5px] w-[200px] h-[200px]">
                        <Image src="/companies/Aisle.png" alt="aurora" width={800} height={100} className="  object-cover p-2  relative z-88" quality={100} priority />

                      </motion.div>


                    </div>

                  </motion.div>
                  <div className='  p-5  max-[900px]:w-[90vw]  lg:w-2/5 xl:w-1/5   left-3  relative  text-[black]'>
                    <h3 className='text-4xl font-bold text-[#63001C]'>Aisle Rocket</h3>
                    <h5 className='text-[#792300]'>front End Developer</h5>
                    <span className="text-[#792300]">2022</span>
                    <p className='lg:w-full md:w-2/3 leading-7 text-[#772406] mt-5'>Aisle Rocket is a digital marketing agency that harnesses the power of data and actionable insights to deliver breakthrough ideas
                      and brand experiences that drive emotional connection and measurable impact.</p> </div>

                </div>







              </div>





            </div>

      
   
*/