import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { motion } from "framer-motion"
import Word from '../components/Animation/Word';
import Text from '../components/Animation/Text';
import { projects } from "../types/project"
import ProjectImage from '../components/ProjectImage/ProjectImage';
import { useRouter } from "next/router";

export default function Home() {

  return (
    <motion.div

    >
      <motion.div
        initial={{
          opacity: 0,
          top: "20rem",

        }}
        animate={{
          opacity: 1,
          top: 0,

        }}
        transition={{
          type: "spring",
          damping: 15,
          stiffness: 300,
          duration: 1
        }}


        className="absolute w-[100wv] h-[100vh] left-0 right-0  " style={{

          backgroundImage: "url(../companies/vector.svg)",
          backgroundRepeat: "no-repeat",
          backgroundAttachment: "fixed",
          backgroundPosition: "top 1% center",
          backgroundSize: "90%"
        }}>


      </motion.div>
      <div className={styles.container}>

        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={styles.main}>

          <div className='flex flex-col w-80 sm:w-96 md:w-10/12 md:items-center relative mt-52'>
            <div>
              <div className="relative">
                <Word className="font-Poppins leading-8	 text-[#0B1727] font-bold text-2xl" word='A DEVELOPER WITH AN EYE FOR PRODUCT AND USER EXPERIENCE' />
              </div>
              <div className=" mt-4 md:w-10/12 sm:w-96 ">
                <Text duration={0.02} className="font-Poppins leading-5 text-[#2E435F] text-sm" text='I will help you design a Minimalistic, and intuitive user interface that  ' />
                <Text duration={0.02} className="font-Poppins leading-5 text-[#2E435F] text-sm" text=' will enthrall and  engage your users' />
              </div>

            </div>
            <div className="flex flex-col items-center md:flex-row md:mt-32">
              <motion.button
                initial={{
                  opacity: 0
                }}
                animate={{
                  opacity: 1
                }}
                transition={{
                  type: "spring",
                  damping: 15,
                  stiffness: 300,
                  duration: 1
                }}
                style={{
                  boxShadow: "0px 58px 23px rgba(121, 113, 234, 0.01), 0px 32px 19px rgba(121, 113, 234, 0.05), 0px 14px 14px rgba(121, 113, 234, 0.09), 0px 4px 8px rgba(121, 113, 234, 0.1), 0px 0px 0px rgba(121, 113, 234, 0.1)",
                }}
                whileHover={{ scale: 1.1 }}
                className="bg-[#576E92] h-14 w-52 mb-24 mt-20 md:mt-0 md:mb-0 md:mr-32"><span className="font-Poppins text-white">View My Work</span></motion.button>
              <motion.button
                initial={{
                  opacity: 0
                }}
                animate={{
                  opacity: 1
                }}
                whileHover={{
                  scale: 1.1
                }}

                className="bg-[#DCE0E6] h-14 w-52" style={{ boxShadow: '0px 87px 35px rgba(11, 23, 39, 0.01), 0px 49px 29px rgba(11, 23, 39, 0.05), 0px 22px 22px rgba(11, 23, 39, 0.09), 0px 5px 12px rgba(11, 23, 39, 0.1), 0px 0px 0px rgba(11, 23, 39, 0.1)' }}>
                <span className='text-[#0B1727] font-Poppins'>Contact Me</span></motion.button>
            </div>
          </div>
          <div className="w-8/12 md:w-10/12 lg:w-7/12 xl:w-5/12 sm:w-6/12 mt-48">
            <Word className="font-Poppins text-xl max-[500px]:text-xl text-[#2E435F] leading-12" word={`Passionate about Technology and obess with learning. I love working at the intersection of creativity and User friendly interfaces`} />
            <motion.button
              initial={{
                opacity: 0
              }}
              animate={{
                opacity: 1
              }}
              whileHover={{
                scale: 1.1,
                boxShadow: "0px 66px 27px rgba(23, 25, 28, 0.01), 0px 37px 22px rgba(23, 25, 28, 0.05), 0px 17px 17px rgba(23, 25, 28, 0.09), 0px 4px 9px rgba(23, 25, 28, 0.1), 0px 0px 0px rgba(23, 25, 28, 0.1)"
              }} className="  bg-[#324670] h-14 w-52 mt-12 mb-32"><span className="font-Poppins text-white">About me</span></motion.button>
          </div>
          <div className="mt-24 mb-24 ">
            <motion.h2
              initial={{ top: '15rem', opacity: 0 }}
              whileInView={{
                top: 0,
                opacity: 1

              }}
              animate={{ opacity: 1 }}
              viewport={{ once: true }}
              transition={{
                type: "spring",
                damping: 15,
                stiffness: 300,
                duration: 1
              }}

              className=' relative  text-6xl max-[500px]:text-4xl font-bold font-Poppins text-[#0B1727] uppercase'>Latest Project</motion.h2>
            <motion.div
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              transition={{
                duration: 1
              }}
              className='bg-[#576E92]  h-[0.2rem] top-1 relative'></motion.div>
          </div>

          <section className="w-full h-full   justify-center items-center " >
            <div className="relative ">
              {projects.slice(0,3).map((project, index) => {
                return (
                 
                    <ProjectImage key={project.name + "__" + project.year} ProjectName={project.name}
                      index={index}
                      hoverImage={project.hoverImages}
                      buttonColor={project.color}
                      reverse={index % 2 === 0 ? true : false}
                      titleColor={project.titleColor} Role={project.Role} Year={project.year} Description={project.description}
                      CompanyImage={project.CompanyImage}
                      color={project.color} />
                  )
              })}
            </div>
          </section>
          <motion.div className="text-[#2E435F] font-bold  relative mt-32">
            <motion.h1 className="text-3xl lg:text-5xl mb-5 relative"
              initial={{
                opacity: 0,

                top: "10rem"
              }}
              whileInView={{

                opacity: 1,
                top: 0
              }}
              transition={{
                type: "spring",
                damping: 12,
                stiffness: 200,
                duration: 1.5
              }}

            >Have a Project in Mind?</motion.h1>
            <motion.div
              initial={{
                scale: 0
              }}
              whileInView={{
                scale: 1
              }}
              transition={{
                type: "spring",
                damping: 12,
                stiffness: 200,
                duration: 1
              }}
              whileHover={{
                boxShadow: `0px 233px 93px rgba(0, 0, 0, 0.01), 0px 131px 79px rgba(0, 0, 0, 0.05), 0px 58px 58px rgba(0, 0, 0, 0.09),
             0px 15px 32px rgba(0, 0, 0, 0.1), 0px 0px 0px rgba(0, 0, 0, 0.1)`,
                scale: 1.1,
                background: 'linear-gradient(180deg, rgba(255, 181, 0, 0.01) 0%, rgba(0, 35, 90, 0.2) 100%)'
              }}
              style={{
                background: "linear-gradient(180deg, rgba(255, 255, 255, 0) 0%, rgba(242, 101, 39, 0.25) 100%)"
              }}
              className=" rounded-full w-52  h-52 m-auto relative mt-10 cursor-pointer">

              <motion.h1
                initial={{
                  opacity: 0,

                  top: 0
                }}


                whileInView={{
                  opacity: 1,

                  top: "5rem"
                }}
                transition={{
                  type: "spring",
                  damping: 12,
                  stiffness: 200,
                  duration: 1
                }}
                className="absolute  whitespace-nowrap  text-[#A74B20]  capitalize  -left-[0.6rem]  text-5xl">Let's Talk</motion.h1>

            </motion.div>


          </motion.div>
        </div>
      </div>

    </motion.div>
  )
}



